In [155]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd
import warnings
warnings.filterwarnings('ignore')
# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
import pandas as pd 
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm, tree
import xgboost 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

# Importing the dataset
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
combine= [df_train, df_test]

for dataset in combine:
    imr = SimpleImputer(missing_values= np.NaN, strategy='mean')
    imr = imr.fit(dataset[['Age']])
    dataset['Age'] = imr.transform(dataset[['Age']]).ravel()

imr = SimpleImputer(missing_values= np.NaN, strategy='most_frequent')
imr = imr.fit(df_train[['Embarked']])
df_train['Embarked'] = imr.transform(df_train[['Embarked']]).ravel()

imr = SimpleImputer(missing_values= np.NaN, strategy='mean')
imr = imr.fit(df_test[['Fare']])
df_test['Fare'] = imr.transform(df_test[['Fare']]).ravel()

for dataset in combine:
    dataset.drop(columns = ['Cabin','PassengerId', 'Name','Ticket'], axis = 1 , inplace = True )

df_train['Fare'] = np.round(df_train['Fare'].astype(float))
df_train['Age'] = np.round(df_train['Age'].astype(float))
df_test['Fare'] = np.round(df_test['Fare'].astype(float))
df_test['Age'] = np.round(df_test['Age'].astype(float))

Y_train = df_train["Survived"].astype(float)
X_train = df_train
X_test  = df_test

X_train['Family'] = X_train.SibSp + X_train.Parch
X_train.drop(['SibSp', 'Parch'], axis = 1 , inplace = True )


X_test['Family'] = X_test.SibSp + X_test.Parch
X_test.drop(['SibSp', 'Parch'], axis = 1 , inplace = True )


#X_train.Sex = X_train.Sex.map({'male':0 , 'female':1})
#X_test.Sex = X_test.Sex.map({'male':0 , 'female':1})

#X_train.Embarked = X_train.Embarked.map({'C':0, 'Q': 1, 'S':2})
#X_test.Embarked = X_test.Embarked.map({'C':0, 'Q': 1, 'S':2})

df_train = df_train[['Age','Sex' ,'Pclass','Fare','Embarked','Family','Survived']]
df_test = df_test[['Age','Sex' ,'Pclass','Fare','Embarked','Family']]



X_train.drop('Survived', axis = 1 , inplace = True )



columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
new = df_train.columns.to_list()
new.remove('Sex')
new_col = ['Female', 'Male'] + new
df_train = pd.DataFrame(np.array(columnTransformer.fit_transform(df_train)), columns= new_col)


columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
new = df_train.columns.to_list()
new.remove('Pclass')
new_col = ['First Class', 'Second Class', 'Third Class'] + new
df_train = pd.DataFrame(np.array(columnTransformer.fit_transform(df_train)), columns= new_col)


columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [7])], remainder='passthrough')
new = df_train.columns.to_list()
new.remove('Embarked')
new_col = ['Emb C', 'Emb Q', 'Emb S'] + new
df_train = pd.DataFrame(np.array(columnTransformer.fit_transform(df_train)), columns= new_col)


#######################



columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
new = df_test.columns.to_list()
new.remove('Sex')
new_col = ['Female', 'Male'] + new
df_test = pd.DataFrame(np.array(columnTransformer.fit_transform(df_test)), columns= new_col)



columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
new = df_test.columns.to_list()
new.remove('Pclass')
new_col = ['First Class', 'Second Class', 'Third Class'] + new
df_test = pd.DataFrame(np.array(columnTransformer.fit_transform(df_test)), columns= new_col)


columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [7])], remainder='passthrough')
new = df_test.columns.to_list()
new.remove('Embarked')
new_col = ['Emb C', 'Emb Q', 'Emb S'] + new
df_test = pd.DataFrame(np.array(columnTransformer.fit_transform(df_test)), columns= new_col)


X_train = df_train.astype(float)
X_test = df_test.astype(float)
X_train.drop('Survived', axis = 1 , inplace = True)


#scalar = StandardScaler()
#scalar.fit(X_train)
#X_train = scalar.fit_transform(X_train)


#scalar.fit(X_test)
#X_test = scalar.fit_transform(X_test)



min_max_scaler = preprocessing.MinMaxScaler()
X_train['Age'] = min_max_scaler.fit_transform(X_train['Age'].values.reshape(-1,1))
X_test['Age'] = min_max_scaler.fit_transform(X_test['Age'].values.reshape(-1,1))

X_train['Fare'] = min_max_scaler.fit_transform(X_train['Fare'].values.reshape(-1,1))
X_test['Fare'] = min_max_scaler.fit_transform(X_test['Fare'].values.reshape(-1,1))

In [156]:
X_train

,Emb C,Emb Q,Emb S,First Class,Second Class,Third Class,Female,Male,Age,Fare,Family
0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.2750,0.013672,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.4750,0.138672,1.0
2,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.3250,0.015625,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.4375,0.103516,1.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.4375,0.015625,0.0
...,...,...,...,...,...,...,...,...,...,...,...
886,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.3375,0.025391,0.0
887,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.2375,0.058594,0.0
888,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.3750,0.044922,3.0
889,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.3250,0.058594,0.0
890,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.4000,0.015625,0.0

In [140]:
#sns.pairplot(df_train[['Age','Sex' ,'Pclass','Fare','Survived','Embarked']], hue="Survived", palette='Set2' )

"""
scaler = StandardScaler()
scaler.fit(X_train.Age.values.reshape(-1,1))
X_train.Age = pd.Series(scaler.fit_transform(X_train.Age.values.reshape(-1,1))[:,0])

scaler.fit(X_train.Fare.values.reshape(-1,1))
X_train.Fare = pd.Series(scaler.fit_transform(X_train.Fare.values.reshape(-1,1))[:,0])

scaler.fit(X_test.Fare.values.reshape(-1,1))
X_test.Fare = pd.Series(scaler.fit_transform(X_test.Fare.values.reshape(-1,1))[:,0])


scaler.fit(X_test.Age.values.reshape(-1,1))
X_test.Age = pd.Series(scaler.fit_transform(X_test.Age.values.reshape(-1,1))[:,0])
"""

'\nscaler = StandardScaler()\nscaler.fit(X_train.Age.values.reshape(-1,1))\nX_train.Age = pd.Series(scaler.fit_transform(X_train.Age.values.reshape(-1,1))[:,0])\n\nscaler.fit(X_train.Fare.values.reshape(-1,1))\nX_train.Fare = pd.Series(scaler.fit_transform(X_train.Fare.values.reshape(-1,1))[:,0])\n\nscaler.fit(X_test.Fare.values.reshape(-1,1))\nX_test.Fare = pd.Series(scaler.fit_transform(X_test.Fare.values.reshape(-1,1))[:,0])\n\n\nscaler.fit(X_test.Age.values.reshape(-1,1))\nX_test.Age = pd.Series(scaler.fit_transform(X_test.Age.values.reshape(-1,1))[:,0])\n'

In [146]:
X_train

array([[-0.48204268, -0.30756234,  0.61583843, ..., -0.59677457,
        -0.50768415,  0.05915988],
       [ 2.0745051 , -0.30756234, -1.62380254, ...,  0.63460743,
         0.78093781,  0.05915988],
       [-0.48204268, -0.30756234,  0.61583843, ..., -0.28892907,
        -0.48754943, -0.56097483],
       ...,
       [-0.48204268, -0.30756234,  0.61583843, ...,  0.01891643,
        -0.18552866,  1.29942929],
       [ 2.0745051 , -0.30756234, -1.62380254, ..., -0.28892907,
        -0.04458563, -0.56097483],
       [-0.48204268,  3.25137334, -1.62380254, ...,  0.17283918,
        -0.48754943, -0.56097483]])

In [161]:
classifiers = []
model1 = xgboost.XGBClassifier(eval_metric='mlogloss')
classifiers.append(model1)


model2 = svm.SVC(C = 5)
classifiers.append(model2)


model3 = tree.DecisionTreeClassifier(criterion= 'entropy', splitter='best')
classifiers.append(model3)


model4 = RandomForestClassifier(criterion='entropy')
classifiers.append(model4)

model5 = LogisticRegression()
classifiers.append(model5)

model6 =KNeighborsClassifier(n_neighbors = 4)
classifiers.append(model6)


model7 = GaussianNB()
classifiers.append(model7)


model8 = Perceptron()
classifiers.append(model8)


model9 = LinearSVC()
classifiers.append(model9)

model10 = SGDClassifier()
classifiers.append(model10)

ModelName = [type(classifiers[i]).__name__ for i in range(0,10)]

Model_Score = []
for clf in classifiers:
    kfold = KFold(n_splits=10, random_state= 0, shuffle= True)
    Model_Score.append(cross_val_score(clf, X_train, Y_train, cv=kfold).mean()*100.0)
ModelDF = pd.DataFrame({'Model' : ModelName, 'Score' : pd.Series(Model_Score)})
ModelDF.sort_values(by = 'Score', ascending= False)

                    Model      Score
0           XGBClassifier  81.373283
3  RandomForestClassifier  80.922597
4      LogisticRegression  80.357054
1                     SVC  80.245943
5    KNeighborsClassifier  79.796504
8               LinearSVC  79.796504
6              GaussianNB  79.119850
9           SGDClassifier  78.565543
2  DecisionTreeClassifier  77.440699
7              Perceptron  71.486891

In [162]:
clf = SVC(C = 5)
clf.fit(X_train, Y_train)
Y_pred= clf.predict(X_test)
Y_pred
Y_pred = Y_pred.astype('int')
submit = pd.read_csv('gender_submission.csv')
submit['Survived'] = pd.Series(Y_pred)
submit.to_csv('KaggleTitanicSubmission.csv', index=False)